-- warehouse/dim_date.sql
-- ══════════════════════════════════════════════════════════════════
--  Dimension: Date
--  Type: Static / Append (generated by transform.py)
--  Grain: one row per calendar day
--  Key: date_sk INTEGER  format YYYYMMDD (e.g. 20240315)
-- ══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS dim_date (
    date_sk         INTEGER      PRIMARY KEY,  -- YYYYMMDD

    -- Calendar fields
    full_date       DATE         NOT NULL,
    year            SMALLINT     NOT NULL,
    quarter         SMALLINT     NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month           SMALLINT     NOT NULL CHECK (month   BETWEEN 1 AND 12),
    month_name      VARCHAR(20)  NOT NULL,
    week            SMALLINT     NOT NULL,     -- ISO week number
    day_of_month    SMALLINT     NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
    day_of_week     SMALLINT     NOT NULL CHECK (day_of_week  BETWEEN 0 AND 6),
                                               -- 0=Monday … 6=Sunday
    day_name        VARCHAR(20)  NOT NULL,

    -- Flags
    is_weekend      BOOLEAN      NOT NULL DEFAULT FALSE,
    is_month_end    BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Derived labels for reporting
    year_quarter    VARCHAR(10)  GENERATED ALWAYS AS
                        (year::TEXT || '-Q' || quarter::TEXT) STORED,
    year_month      VARCHAR(10)  GENERATED ALWAYS AS
                        (year::TEXT || '-' || LPAD(month::TEXT, 2, '0')) STORED
);

CREATE INDEX IF NOT EXISTS idx_dim_date_full_date    ON dim_date(full_date);
CREATE INDEX IF NOT EXISTS idx_dim_date_year_month   ON dim_date(year, month);
CREATE INDEX IF NOT EXISTS idx_dim_date_year_quarter ON dim_date(year_quarter);
CREATE INDEX IF NOT EXISTS idx_dim_date_is_weekend   ON dim_date(is_weekend);

-- ── Convenience view: last N days ─────────────────────────────────────────────
CREATE OR REPLACE VIEW v_last_90_days AS
SELECT *
FROM   dim_date
WHERE  full_date >= CURRENT_DATE - INTERVAL '90 days'
ORDER  BY full_date DESC;

COMMENT ON TABLE dim_date IS
    'Date dimension. date_sk format is YYYYMMDD integer. '
    'Spans ±30 days around the actual data range.';

COMMENT ON COLUMN dim_date.day_of_week IS
    '0 = Monday, 6 = Sunday (ISO weekday convention).';
